#!/bin/sh

echo $(date) restarted >> /var/log/projects/anklav/restart.log
exec chpst -u www /home/www/projects/anklav/ENV/bin/python /home/www/projects/anklav/src/manage.py runfcgi errlog=/var/log/projects/anklav/fcgi-error.log method=prefork socket=/home/www/projects/anklav/fcgi.sock pidfile=/home/www/projects/anklav/pid daemonize=false
